module.exports = Object.freeze({
  viljelija: 'Viljelijä',
  viljelijanPuhelin: 'Viljelijän puhelin',
  katuosoite: 'Katuosoite',
  email: 'Sähköposti',
  postiosoite: 'Postiosoite',
  tilatunnus: 'Viljelijän tilatunnus',
  tarkastuttaja: 'Tarkastuttaja',
  tarkastuttajanPuhelin: 'Tarkastuttajan puhelin',
  viljelysTarkastaja: 'Viljelystarkastaja',
  laji: 'Laji',
  lajike: 'Lajike',
  kylvoisyys: 'Kylvöisyys',
  tuotantotapa: 'Tuotantotapa',
  sijaintikunta: 'Sijaintikunta',
  kantasiemen: 'Kantasiemen',
  pyydettyPintaAla: 'Pyydetty pinta-ala',
  satoarvio: 'Satoarvio',
  pyydettySiemenluokka: 'Pyydetty siemenluokka',
  yleisarvosana: 'Yleisarvosana',
  ehdotettuSiemenluokka: 'Ehdotettu siemenluokka',
  viljelysJatkamiskelpoinen: 'Viljelys jatkamiskelpoinen',
  hyvaksytyksiEhdotettu: 'Hyväksytyksi ehdotettu',
  hylatyksiEhdotettu: 'Hylätyksi ehdotettu',
  rikkakasvitViljelyksella: 'Rikkakasvit viljelyksellä',
  lisähuomiot: 'Lisähuomiot',
});
